apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-sentiment-deployment
  labels:
    app: ngnm-sentimentinx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nm-sentiment
  template:
    metadata:
      labels:
        app: nm-sentiment
    spec:
      containers:
      - name: nm-sentiment
        image: quay.io/mpaulgreen/nm-sentiment:0.0.5
        ports:
        - containerPort: 8080