# NOTE: this is a sample configuration file for a sentiment-analysis server
endpoints:
    - task: sentiment-analysis
      route: /predict
      model: zoo:nlp/sentiment_analysis/distilbert-none/pytorch/huggingface/sst2/pruned80_quant-none-vnni